### ISSUE TITLE
Test failure on OS X 

### ISSUE THREAD

**Issue by dchest** [PuerkitoBio/throttled#4]
When running tests on OS X Yosemite 10.10.2 (14C1514), I get the following failures:

```
~/Documents/goproj/src/github.com/PuerkitoBio/throttled $ go test
--- FAIL: TestInterval (17.12s)
	interval_test.go:91: 3: expected RPS to be around 1000, got 738.903533
--- FAIL: TestIntervalVary (50.83s)
	interval_test.go:91: 3: expected RPS to be around 1000, got 754.430161
	interval_test.go:91: 3: expected RPS to be around 1000, got 756.398603
FAIL
exit status 1
FAIL	github.com/PuerkitoBio/throttled	73.583s
```

**Comment by PuerkitoBio** [comment]
Yeah it's a test that gives a little room for errors, but that may not be enough on all machines. If you look at the code, it allows a 20% difference from the theoretical rate, and you are slightly outside that range.

It's not a test that I run on Travis because of that potential random failure. You can either adjust the wiggle room or skip it by passing the -short flag to go test. I'd like to have a more reliable way to test this, haven't thought about it much to be honest...

**Comment by dchest** [comment]
I see, thank you. I'm closing this issue and will think about more reliable test.
