### ISSUE TITLE
VaryBy IP address

### ISSUE THREAD

**Issue by dchest** [PuerkitoBio/throttled#6]
Since many clients use a random port for querying, `RemoteAddr` is not a great option for rate limiting, because it contains a port number. Would you consider adding `IPAddr` (or something like this) option to `VaryBy` struct, which will strip port? Of course, this can be done with `VaryBy.Custom`, but I think limiting by IP address is a pretty common scenario.

I can send a pull request if you like.

**Comment by PuerkitoBio** [comment]
Hi Dmitry,

I agree with you that `RemoteAddr` is not reliable, and this is a common scenario to want to limit on IP address. But as mentioned in this issue: https://github.com/PuerkitoBio/throttled/issues/1 getting the actual usable IP address is quite involved, and just removing the port to create a new `IPAddr` option would not be terribly more useful. That's why for that case I believe it is best to use `Custom`.

Martin

**Comment by dchest** [comment]
Thanks!

**Comment by flyingmutant** [comment]
@PuerkitoBio, can you please explain why `VaryBy.Custom` is marked as `DEPRECATED`?

**Comment by PuerkitoBio** [comment]
Hi Gregory,

All original features are still supported in the v1 of `throttled` (https://godoc.org/gopkg.in/throttled/throttled.v1), however I've since passed the torch to a small group of contributors to free myself a bit for other projects. They are now in charge of maintaining and evolving the package (it started when @metcalf submitted a great PR that turned things around quite a bit). This is why some things are marked as deprecated for the v2, though I'm not sure why the `VaryBy.Custom` is specifically marked as such, maybe they can jump in and give you better information about that.

Thanks,
Martin

**Comment by metcalf** [comment]
Hi @flyingmutant! 

@brandur and I have taken over maintainership of throttled. Part of this effort was a [relatively large PR](https://github.com/throttled/throttled/pull/9) to narrow the interface to throttled while retaining compatibility for what we expected were the most common use cases.

The `HTTPRateLimiter` (or its deprecated alias `Throttler`) now take `VaryBy` as an interface rather than using a concrete type. If you want to vary by custom logic, you can pass any type that satisfies the interface. If you want to combine the concrete `VaryBy` with your own custom logic, you can wrap it with your own arbitrary logic so long as it implements the interface. For example, if I want to vary by the IP address and whether the request has TLS connection information you'd want something like:
```
type myVaryBy struct {}

func (*m myVaryBy) Key(r *http.Request) string {
    return fmt.Sprintf("%t\n%s", r.TLS != nil, throttled.VaryBy{RemoteAddr: true}.Key())
}
```

If that isn't workable for your use case I'd be interested to hear more. Separately, I'd value any comments in the overall interface of throttled as it stands today.

**Comment by flyingmutant** [comment]
@metcalf, thanks a lot — I just somehow missed the `interface { Key(*http.Request) string }` bit.
